- name: Google Cloud SDK
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure google cloud sdk
      register: gcloud_cli_installed
      homebrew_cask:
        name: google-cloud-sdk

    - name: Perform first-run experience
      command: gcloud init
      when: gcloud_cli_installed.changed
