- name: git
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Homebrew packages
      homebrew:
        name: "{{ item }}"
      loop:
        - git
        - gpg

    - name: Install Github Desktop (macOS)
      homebrew_cask:
        name: github
