- name: git
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Homebrew packages
      homebrew:
        name: "{{ item }}"
      loop:
        - git
        - git-gui
        - git-lfs
        - gpg
        - gnu-sed
        - ripgrep
