- name: git
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure git packages
      homebrew:
        name: "{{ item }}"
      loop:
        - git
        - gnupg
        - pinentry-mac

    - name: Update agent
      copy:
        dest: ~/.gnupg/gpg-agent.conf
        content: |
          pinentry-program /usr/local/bin/pinentry-mac

    - name: Ensure Github Desktop
      homebrew_cask:
        name: github
