#########################################################################################
#
#  Note that import order here is important, so rearranging import lists
#  is *not* recommended.
#
#########################################################################################

- name: Configure machine for development work
  hosts: 127.0.0.1
  connection: local

##### Operating system packages and configuration

- import_playbook: core.yaml
- import_playbook: dev-folders/core.yaml
- import_playbook: fonts/core.yaml
- import_playbook: omz/core.yaml

##### Developer tools

# Visual Studio Code
- import_playbook: vscode/core.yaml

# Ansible
- import_playbook: ansible/vscode.yaml

# Docker
- import_playbook: docker/core.yaml
- import_playbook: docker/vscode.yaml

# .NET Core
- import_playbook: dotnet/core.yaml
- import_playbook: dotnet/vscode.yaml

# git
- import_playbook: git/core.yaml
- import_playbook: git/vscode.yaml

# Kubernetes
- import_playbook: kubectl/core.yaml
- import_playbook: kubectl/vscode.yaml

# Virtualization
- import_playbook: virtualization/core.yaml

# Mono (.NET Framework)
- import_playbook: mono/core.yaml
- import_playbook: mono/vscode.yaml

# NodeJS
- import_playbook: nodejs/core.yaml
- import_playbook: nodejs/vscode.yaml

# Postman
- import_playbook: postman/core.yaml

# Python
- import_playbook: python/core.yaml
- import_playbook: python/vscode.yaml

# Ruby
- import_playbook: ruby/core.yaml
- import_playbook: ruby/vscode.yaml

# Google Cloud CLI
- import_playbook: google-cloud-cli/core.yaml

# Terraform CLI
- import_playbook: terraform/core.yaml

# IRC
- import_playbook: irc/core.yaml

# window arrangement
- import_playbook: hammerspoon/core.yaml

# password management
- import_playbook: lastpass/core.yaml

# vim
- import_playbook: vim/core.yaml

# music
- import_playbook: pianobar/core.yaml

##### Applications (free)

# Firefox
- import_playbook: firefox/core.yaml

# Google Chrome
- import_playbook: google-chrome/core.yaml

# Google Chat
- import_playbook: google-chat/core.yaml

# Prettier version of ping w/ graphs
- import_playbook: prettyping/core.yaml

# Slack desktop application
- import_playbook: slack/core.yaml

##### Applications (commercial license required)

# alfred
- import_playbook: alfred/core.yaml

# RDP
- import_playbook: royal/core.yaml
