- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    # macOS

    - name: Update Homebrew and all packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: Install core packages
      homebrew:
        name: "{{ item }}"
      loop:
        - bat
        - htop
        - jq
