- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    # Common

    - name: Create ~/bin
      file:
        path: ~/bin
        state: directory
        mode: 0700

    - name: Add ~/bin to PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH=$PATH:~/bin

    # macOS

    - name: Update Homebrew and all packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: Install core packages
      homebrew:
        name: "{{ item }}"
      loop:
        - bat
        - htop
        - jq

    - name: Add GNU tar to the PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH=/usr/local/opt/gnu-tar/libexec/gnubin:$PATH
