- name: Core OS customization
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure software updates daily
      osx_defaults:
        domain: com.apple.SoftwareUpdate
        key: ScheduleFrequency
        type: int
        value: 1
        state: present

    - name: Increase sound quality for Bluetooth headphones/headsets
      osx_defaults:
        domain: com.apple.BluetoothAudioAgent
        key: "Apple Bitpool Min (editable)"
        type: int
        value: 40
        state: present

    - name: Require password after sleep or screen saver begins
      osx_defaults:
        domain: com.apple.screensaver
        key: askForPassword
        type: int
        value: 1
        state: present

    - name: Require password immediately after sleep or screen saver begins
      osx_defaults:
        domain: com.apple.screensaver
        key: askForPasswordDelay
        type: int
        value: 0
        state: present

    - name: Save screenshots to desktop
      osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: ${HOME}/Desktop
        state: present

    - name: Save screenshots as png
      osx_defaults:
        domain: com.apple.screencapture
        key: type
        type: string
        value: "png"
        state: present

    - name: Change new window target
      osx_defaults:
        domain: com.apple.finder
        key: NewWindowTarget
        type: string
        value: PfDe
        state: present

    - name: Set new window to dev
      osx_defaults:
        domain: com.apple.finder
        key: NewWindowTargetPath
        type: string
        value: file://${HOME}/dev/
        state: present

    - name: Show file extensions
      osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true
        state: present

    - name: Search current folder
      osx_defaults:
        domain: com.apple.finder
        key: FXDefaultSearchScope
        type: string
        value: SCcf
        state: present

    - name: No warning for extension change
      osx_defaults:
        domain: com.apple.finder
        key: FXEnableExtensionChangeWarning
        type: bool
        value: false
        state: present

    - name: Skip DS_Store creation
      osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true
        state: present

    - name: Skip DS_Store creation usb
      osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteUSBStores
        type: bool
        value: true
        state: present

    - name: Empty trash securely
      osx_defaults:
        domain: com.apple.finder
        key: EmptyTrashSecurely
        type: bool
        value: true
        state: present

    - name: Disable the Are you sure you want to open this application? dialog
      osx_defaults:
        domain: com.apple.LaunchServices
        key: LSQuarantine
        type: bool
        value: false
        state: present

    - name: Disable automatic period substitution as it’s annoying when typing code
      osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticPeriodSubstitutionEnabled
        type: bool
        value: false
        state: present

    - name: Disable press-and-hold for keys in favor of key repeat
      osx_defaults:
        domain: NSGlobalDomain
        key: ApplePressAndHoldEnabled
        type: bool
        value: false
        state: present

    - name: Key Repeat
      osx_defaults:
        domain: NSGlobalDomain
        key: KeyRepeat
        type: int
        value: 2
        state: present

    - name: Faster repeat rate
      osx_defaults:
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        type: int
        value: 25
        state: present

    - name: Disable machine sleep while charging
      become: yes
      shell:
        cmd: "pmset -c sleep 0"

    - name: Speed up mouse
      osx_defaults:
        domain: com.apple.mouse
        key: scaling
        type: float
        value: 2.5
        state: present
      become: yes

    - name: enable right click. mouse
      osx_defaults:
        domain: "{{ item }}"
        key: MouseButtonMode
        value: TwoButton
      with_items:
        - com.apple.driver.AppleBluetoothMultitouch.mouse
        - com.apple.AppleMultitouchMouse

    - name: Auto hide dock
      osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: int
        value: 1
        state: present

    - name: Tap to click
      osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: Clicking
        type: int
        value: 1
        state: present

    - name: Three finger drag
      osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadThreeFingerDrag
        type: int
        value: 1
        state: present

    - name: Verticle Swipe Gesture
      osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadThreeFingerVertSwipeGesture
        type: int
        value: 2
        state: present
