
- name: Core OS customization
  hosts: 127.0.0.1
  connection: local

  tasks:

    - osx_defaults: # Ensure software updates daily
        domain: com.apple.SoftwareUpdate
        key: ScheduleFrequency
        type: int
        value: 1
        state: present

    - osx_defaults: # Increase sound quality for Bluetooth headphones/headsets
        domain: com.apple.BluetoothAudioAgent
        key: 'Apple Bitpool Min (editable)'
        type: int
        value: 40
        state: present

    - osx_defaults: # Require password after sleep or screen saver begins
        domain: com.apple.screensaver
        key: askForPassword
        type: int
        value: 1
        state: present

    - osx_defaults: # Require password immediately after sleep or screen saver begins
        domain: com.apple.screensaver
        key: askForPasswordDelay
        type: int
        value: 0
        state: present

    - osx_defaults: # Save screenshots to desktop
        domain: com.apple.screencapture
        key: location
        type: string
        value: ${HOME}/Desktop
        state: present

    - osx_defaults: # Save screenshots as png
        domain: com.apple.screencapture
        key: type
        type: string
        value: 'png'
        state: present

    - osx_defaults: # Change new window target
        domain: com.apple.finder
        key: NewWindowTarget
        type: string
        value: PfDe
        state: present

    - osx_defaults: # Set new window to dev
        domain: com.apple.finder
        key: NewWindowTargetPath
        type: string
        value: file://${HOME}/dev/
        state: present

    - osx_defaults: # Show hidden files
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true
        state: present

    - osx_defaults: # Show file extensions
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true
        state: present

    - osx_defaults: # Search current folder
        domain: com.apple.finder
        key: FXDefaultSearchScope
        type: string
        value: SCcf
        state: present

    - osx_defaults: # No warning for extension change
        domain: com.apple.finder
        key: FXEnableExtensionChangeWarning
        type: bool
        value: false
        state: present

    - osx_defaults: # Skip DS_Store creation
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true
        state: present

    - osx_defaults: # Skip DS_Store creation usb
        domain: com.apple.desktopservices
        key: DSDontWriteUSBStores
        type: bool
        value: true
        state: present

    - osx_defaults: # Disable trash empty warning
        domain: com.apple.finder
        key: WarnOnEmptyTrash
        type: bool
        value: false
        state: present

    - osx_defaults: # Empty trash securely
        domain: com.apple.finder
        key: EmptyTrashSecurely
        type: bool
        value: true
        state: present

    - osx_defaults: # Disable the Are you sure you want to open this application? dialog
        domain: com.apple.LaunchServices
        key: LSQuarantine
        type: bool
        value: false
        state: present

    - osx_defaults: #  Disable automatic period substitution as it’s annoying when typing code
        domain: NSGlobalDomain
        key: NSAutomaticPeriodSubstitutionEnabled
        type: bool
        value: false
        state: present

    - osx_defaults: # Disable press-and-hold for keys in favor of key repeat
        domain: NSGlobalDomain
        key: ApplePressAndHoldEnabled
        type: bool
        value: false
        state: present

    - osx_defaults: # Key Repeat
        domain: NSGlobalDomain
        key: KeyRepeat
        type: int
        value: 2
        state: present

    - osx_defaults: # Faster repeat rate
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        type: int
        value: 25
        state: present

    - name: Disable machine sleep while charging
      become: yes
      shell:
        cmd: "pmset -c sleep 0"

    - osx_defaults: # Disable dashboard
        domain: com.apple.dashboard
        key: mcx-disabled
        type: bool
        value: true
        state: present

    - osx_defaults: # Speed up mouse
        domain: com.apple.mouse
        key: scaling
        type: float
        value: 2.5
        state: present
      become: yes

    - osx_defaults: # Auto hide dock
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
        state: present

    - osx_defaults: # Tap to click
        domain: com.apple.AppleMultitouchTrackpad
        key: Clicking
        type: int
        value: 1
        state: present

    - osx_defaults: # Three finger drag
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadThreeFingerDrag
        type: int
        value: 1
        state: present

    - osx_defaults: # Horizontal Swipe Gesture
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadThreeFingerHorizSwipeGesture
        type: int
        value: 0
        state: present

    - osx_defaults: # Verticle Swipe Gesture
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadThreeFingerVertSwipeGesture
        type: int
        value: 0
        state: present

    - osx_defaults: # Right edge Swipe Gesture
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadTwoFingerFromRightEdgeSwipeGesture
        type: int
        value: 0
        state: present
    - name: Ensure software updates daily (macOS)
      shell:
        cmd: "defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1"

    - name: Increase sound quality for Bluetooth headphones/headsets (macOS)
      shell:
        cmd: "defaults write com.apple.BluetoothAudioAgent 'Apple Bitpool Min (editable)' -int 40"

    - name: Show file extensions (macOS)
      shell:
        cmd: "defaults write NSGlobalDomain AppleShowAllExtensions -bool true"

    - name: No warning for extension change (macOS)
      shell:
        cmd: "defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false"

    - name: Skip DS_Store creation (macOS)
      shell:
        cmd: "defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true"

    - name: Skip DS_Store creation usb (macOS)
      shell:
        cmd: "defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true"

    - name: Disable the Are you sure you want to open this application? dialog (macOS)
      shell:
        cmd: "defaults write com.apple.LaunchServices LSQuarantine -bool false"

    - name:  Disable automatic period substitution as it’s annoying when typing code (macOS)
      shell:
        cmd: "defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false"

    - name: Disable press-and-hold for keys in favor of key repeat (macOS)
      shell:
        cmd: "defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false"

    - name: Key Repeat (macOS)
      shell:
        cmd: "defaults write NSGlobalDomain KeyRepeat -int 20"

    - name: Faster repeat rate (macOS)
      shell:
        cmd: "defaults write NSGlobalDomain InitialKeyRepeat -int 20"

    - name: Disable machine sleep while charging (macOS)
      shell:
        cmd: "pmset -c sleep 0"
