- name: Folder Structure
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure dev folder
      file:
        path: ~/dev
        state: directory
        mode: 0700
    - name: Ensure clones folder
      file:
        path: ~/dev/clones
        state: directory
        mode: 0700
    - name: Ensure cruft folder
      file:
        path: ~/dev/cruft
        state: directory
        mode: 0700
