- name: Pianobar (customization)
  hosts: 127.0.0.1
  connection: local


  tasks:
    - set_fact: user="{{ lookup('env','ANSIBLE_PIANO_USER') }}"
    - set_fact: pw="{{ lookup('env','ANSIBLE_PIANO_PW') }}"

    - name: Ensure config folder exists
      file:
        path: ~/.config/pianobar
        state: directory
        mode: 0700

    - name: Ensure configuration
      template:
        src: config.j2
        dest: ~/.config/pianobar/config
      vars:
        user: env_user
        pw: env_pw

    - name: Ensure pianobar aliases
      blockinfile:
        path: ~/.zshrc
        marker: "### {mark} Ansible managed: pianobar customizations"
        block: |
          alias p='pianobar 2>/dev/null'
