- name: Docker
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure Docker CLI components
      homebrew:
        name: docker-compose

    - name: Ensure Docker engine
      homebrew_cask:
        name: docker
        state: present
        accept_external_apps: true
