- name: Docker
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Docker CLI components (macOS)
      homebrew:
        name: docker-compose

    - name: Install Docker engine (macOS)
      homebrew_cask:
        name: docker
