- name: Docker (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add custom Docker commands
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Docker customization"
        block: |
          alias dc='docker-compose'
          alias docker-rmi='docker images -aq -f dangling=true | xargs docker rmi'
          alias docker-rmc='docker ps -aq | xargs docker rm'
          alias docker-kill='docker ps -aq | xargs docker kill'
          alias docker-update-images='docker images |grep -v REPOSITORY|awk '{print $1}'|xargs -L1 docker pull'
