- name: fonts
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Tap Font Cask
      homebrew_tap:
        name: homebrew/cask-fonts

    - name: Ensure custom fonts
      homebrew_cask:
        name: "{{ item }}"
      loop:
        - font-victor-mono
        - font-fira-code
