- name: VS Code (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure vscode extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - aaron-bond.better-comments
        - bierner.markdown-checkbox
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - fernandoescolar.vscode-solution-explorer
        - kisstkondoros.vscode-codemetrics
        - mhutchie.git-graph
        - ms-azuretools.vscode-docker
        - ms-dotnettools.csharp
        - ms-vscode-remote.remote-containers
        - ms-vscode.azure-account
        - ms-vscode.hexeditor
        - thibault-vanderseypen.i18n-json-editor
        - uctakeoff.vscode-counter
        - vscode-icons-team.vscode-icons
        - wix.vscode-import-cost

    - name: Ensure ~/.config folder exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Ensure link
      file:
        path: ~/.config/Code
        src: ~/Library/Application Support/Code
        state: link

    - name: Ensure VS Code preferences
      copy:
        src: settings.json
        dest: ~/.config/Code/User/settings.json
