- name: VS Code (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure vscode extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - ahmadawais.shades-of-purple
        - akamud.vscode-theme-onelight
        - andrewmarkle.primer-light
        - anseki.vscode-color
        - bierner.markdown-preview-github-styles
        - chrmarti.regex
        - DavidAnson.vscode-markdownlint
        - dbaeumer.vscode-eslint
        - DotJoshJohnson.xml
        - eamodio.gitlens
        - EditorConfig.EditorConfig
        - Equinusocio.vsc-material-theme
        - equinusocio.vsc-material-theme-icons
        - esbenp.prettier-vscode
        - fabiospampinato.vscode-diff
        - fayras.simple-new-file
        - felipecaputo.git-project-manager
        - GitHub.vscode-pull-request-github
        - googlecloudtools.cloudcode
        - Horla.horla-light-theme
        - Hyzeta.vscode-theme-github-light
        - idleberg.hopscotch
        - johnpapa.vscode-peacock
        - johnpapa.winteriscoming
        - karigari.chat
        - liviuschera.noctis
        - mechatroner.rainbow-csv
        - mkxml.vscode-filesize
        - ms-azuretools.vscode-docker
        - ms-dotnettools.csharp
        - ms-mssql.mssql
        - ms-python.anaconda-extension-pack
        - ms-python.python
        - ms-vscode.atom-keybindings
        - ms-vscode.vscode-typescript-tslint-plugin
        - ms-vsliveshare.vsliveshare
        - ms-vsliveshare.vsliveshare-audio
        - ms-vsliveshare.vsliveshare-pack
        - naumovs.color-highlight
        - PKief.material-icon-theme
        - qinjia.seti-icons
        - rbbit.typescript-hero
        - redhat.vscode-yaml
        - richie5um2.vscode-sort-json
        - streetsidesoftware.code-spell-checker
        - teabyii.ayu
        - uloco.theme-bluloco-light
        - VisualStudioExptTeam.vscodeintellicode
        - vmsynkov.colonize
        - vscode-icons-team.vscode-icons
        - vscodevim.vim
        - whizkydee.material-palenight-theme
        - wmaurer.change-case
        - ziishaned.livereload

    - name: Ensure ~/.config folder exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Ensure link
      file:
        path: ~/.config/Code
        src: ~/Library/Application Support/Code
        state: link

    - name: Ensure VS Code preferences
      copy:
        src: settings.json
        dest: ~/.config/Code/User/settings.json

    - name: Ensure VS Code key bindings
      copy:
        src: keybindings.json
        dest: ~/.config/Code/User/keybindings.json
