- name: Oh my zsh (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure enhanced terminal prompt
      blockinfile:
        dest: ~/.zshrc
        marker: "### {mark} Ansible managed: prompt"
        block: |
          BULLETTRAIN_PROMPT_ORDER=(
            time
            context
            dir
            nvm
            git
            cmd_exec_time
          )

          BULLETTRAIN_EXIT_SHOW=true
          BULLETTRAIN_PROMPT_CHAR=❯

    - name: Ensure custom aliases
      blockinfile:
        dest: ~/.zshrc
        marker: "### {mark} Ansible managed: aliases"
        block: |
          alias zshconfig='vim ~/.zshrc'
          alias ohmyzsh='vim ~/.oh-my-zsh'
          alias home='deactivate; cd ~; clear'
          alias dev='deactivate; cd ~/dev; clear'
          alias grep='grep --colour=auto'
          alias ls='ls -GFh'

    - name: Ensure extra configuration
      file:
        path: ~/.zshenv
        state: touch
        mode: 0744

    - name: Ensure extra configuration is used
      blockinfile:
        dest: ~/.zshrc
        marker: "### {mark} Ansible managed: env"
        block: |
          source ~/.zshenv
