- name: .NET
  hosts: 127.0.0.1
  connection: local

  vars:
    dotnet_versions:
      - "2.1"
      - "3.1"

  tasks:
    - name: Ensure .NET SDK installer
      get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: /usr/local/bin/dotnet-install
        mode: 0755

    - name: Ensure .NET SDK
      shell: dotnet-install -c {{ item }}
      register: dotnet_sdk_installed_mac
      loop: "{{ dotnet_versions }}"
      args:
        creates: ~/.dotnet/sdk/{{ item }}.*/.version

    - name: Ensure dotnet shortcut
      file:
        path: /usr/local/bin/dotnet
        src: ~/.dotnet/dotnet
        state: link

    # Common

    - name: Perform first-run experience
      command: dotnet new
      when: dotnet_sdk_installed_mac.changed

    - name: Ensure environment variables
      blockinfile:
        path: ~/.zshrc
        marker: "### {mark} Ansible managed: .NET Core enhancement"
        block: |
          export PATH=$PATH:$HOME/.dotnet/tools
