- name: .NET Core
  hosts: 127.0.0.1
  connection: local

  vars:
    is_ubuntu_focal: "{{ ansible_distribution_release == 'focal' }}"

  tasks:
    - name: Install global tools
      command: dotnet tool install -g {{ item }}
      args:
        creates: ~/.dotnet/tools/.store/{{ item }}
      loop:
        - coverlet.console
        - dotnet-depends
        - dotnet-format
        - dotnet-outdated
        - dotnet-reportgenerator-globaltool
        - dotnet-retire
      when: not is_ubuntu_focal
