- name: .NET Core (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure vscode extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - formulahendry.dotnet-test-explorer # .NET Core Test Explorer
        - ms-dotnettools.csharp # C#
