- name: kubectl (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure vscode extensions
      command: code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
      args:
        creates: ~/.vscode/extensions/ms-kubernetes-tools.vscode-kubernetes-tools-*/package.json
