- name: NodeJS (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure vscode extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - vmsynkov.colonize
        - dbaeumer.vscode-eslint
        - eg2.vscode-npm-script
        - christian-kohler.npm-intellisense
        - esbenp.prettier-vscode
