- name: irssi (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure config folder exists
      file:
        path: ~/.irssi
        state: directory
        mode: 0700

    - name: Ensure custom configuration
      copy:
        src: config
        dest: ~/.irssi/config
