- name: Ansible (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure vscode extensions
      command: code --install-extension redhat.ansible
      args:
        creates: ~/.vscode/extensions/redhat.ansible-*/package.json
